### PR TITLE
Enable ppc64le architecture support

### PR DESCRIPTION
**Pull request by Vaibhav-Nazare**
This PR introduces support for the ppc64le architecture, extending the project's usability across multiple architectures.

### CODE REVIEW

**Comment by jankalinic** [comment]
Thank you for the PR. I believe we should merge #1246 first and include these changes afterwards.

**Review by MikeEdgar — CHANGES_REQUESTED** [review]
@Vaibhav-Nazare thanks for the PR. As Jan mentioned, there was another PR #1246 to make updates to these files, resulting in the conflict. Please rebase and update the same three files to specify the new platform in the `PLATFORMS` environment variable that is already present in each job.

**Review by jankalinic — APPROVED** [review]
I have not tried the changes, but overall looks good. Thank you!

**Comment by jankalinic** [comment]
Wonder If 

>  #14 [linux/ppc64le 3/3] RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]
#14 0.773 time="2024-12-03T05:08:54Z" level=warning msg="unable to set termination log path" error="open /dev/termination-log: permission denied"

AND

>#15 [linux/arm64 3/3] RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]
#15 0.801 time="2024-12-03T05:08:54Z" level=fatal msg="could not start pprof endpoint: listen tcp 127.0.0.1:6060: bind: address already in use"
#15 ERROR: process "/bin/opm serve /configs --cache-dir=/tmp/cache --cache-only" did not complete successfully: exit code: 1

Is just build failure. Re-runing the job now. Please do not merge just yet, this needs to be fixed.

**Comment by MikeEdgar** [comment]
I have definitely seen `listen tcp 127.0.0.1:6060: bind: address already in use` before. It looks like perhaps some race condition that only becomes more likely with 3 architectures being built.

**Comment by Vaibhav-Nazare** [comment]
> I have definitely seen `listen tcp 127.0.0.1:6060: bind: address already in use` before. It looks like perhaps some race condition that only becomes more likely with 3 architectures being built.

I have seen this too on the first run that happened when I created the MR, but as I pulled in some changes and the build was triggered again,it got passed.

**Comment by MikeEdgar** [comment]
> I have seen this too on the first run that happened when I created the MR, but as I pulled in some changes and the build was triggered again,it got passed.

Yeah, I think as long as the `RUN ["/bin/opm", "serve", "/configs", "--cache-dir=/tmp/cache", "--cache-only"]` command in the catalog Dockerfile does not run concurrently for any two architectures, it's fine. I think adding `network: none` [1] on the catalog build/push actions may help, but you don't need to include that here since it's an existing problem.

[1] https://docs.docker.com/reference/cli/docker/buildx/build/#network

**Pull request merged**
