### PR TITLE
Disable persisted cache for API responses, add refresh button

### PR DESCRIPTION
**Pull request by riccardo-forina**
This should disable any persisted cache for all API responses in the app.

It also adds a "Last updated" info on every page, in the header. The messages page will not show this, as the data refresh is handled by the table in the body.

image

### CODE REVIEW

**Comment by riccardo-forina** [comment]
@MikeEdgar this should be good to go now

**Review by MikeEdgar — APPROVED** [review]

**Comment by MikeEdgar** [comment]
@riccardo-forina there are two playwright tests failing (both browsers) that look like they might be legitimate errors
```

  4 failed
    [chromium] › MessagesPage.test.tsx:3:5 › Messages page ─────────────────────────────────────────
    [chromium] › PartitionsPage.test.tsx:3:5 › Partitions page ─────────────────────────────────────
    [firefox] › MessagesPage.test.tsx:3:5 › Messages page ──────────────────────────────────────────
    [firefox] › PartitionsPage.test.tsx:3:5 › Partitions page ──────────────────────────────────────
```

**Comment by riccardo-forina** [comment]
Well the test suite's been completely updated to reuse the navigation bits and the auth bits as well. It should be easier to grok and maintain, and should pass the checks

**Review by MikeEdgar — APPROVED** [review]
LGTM, ready to merge?

**Comment by riccardo-forina** [comment]
yep!

**Pull request merged**
